name: CI Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Docker Compose CLI plugin
        run: |
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose
          docker compose version

      - name: Start Docker Compose services
        run: |
          docker compose up -d
          docker ps

      - name: Wait for services to be healthy
        run: sleep 20

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Run tests
        run: ./mvnw clean verify

      - name: Stop Docker Compose services
        if: always()
        run: docker compose down